#python -m lingua.stool config=apps/main/configs/llama2_7B.yaml nodes=32 account=fair_amaia_cw_codegen qos=lowest
dump_dir: ${oc.env:LINGUA_DUMP_DIR}
name: ${oc.env:RUN_NAME,spike_run_debug}
steps: 1900
grad_acc_steps: 16
probe_freq: 100

seed: 777
optim:
  lr: 3.0e-4
  beta2: 0.95
  weight_decay: 0.1
  cycle_length: 20.0
  warmup: 95
  lr_min_ratio: 0.0
  clip: 1.0
  lm_head:
    type: null
    lr: null
    momentum: 0.9

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 4096
  n_layers: 32
  n_heads: 32
  megatron_init: true
  init_base_std: 0.01
  qk_norm: true
  rmsnorm_scale: true
  norm_eps: 1e-6
  z_loss: false
  mu_centering: false
  vocab_chunk_size: null
  rope_theta: 100_000
  ffn_dim_multiplier: 1.0
  multiple_of: 256

data:
  root_dir: ${oc.env:LINGUA_DATA_ROOT}
  sources:
    fineweb_edu_10bt_shuffled: 1.0
  batch_size: 1
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: false
  tokenizer:
    # name: tiktoken
    # path: ${oc.env:LLAMA3_TOKENIZER_PATH}
    name: sp
    path: ${oc.env:MEGATRON_LLAMA_TOKENIZER_MODEL,data/llama-7b/tokenizer.model}

profiling:
  run: false
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 1000000000
    keep: -1
  eval:
    every: 1000000000
    keep: 3

logging:
  freq: 1
  light_freq: 1
  wandb_light_freq: 1
  wandb:
      entity: ${oc.env:WANDB_ENTITY}
      project: lingua_runs
      name: ${name}

async_eval_gpus: null
eval: null